### PR TITLE
fix: don't panic on non minimal varints

### LINKED ISSUE #282: Unsafe unwrap could cause an application to panic
https://github.com/multiformats/rust-multihash/blob/8e14b1919bb0f60daa63f0b070278a2963603790/src/multihash.rs#L368

The `unwrap()` here might cause some crash using the library if an error occurred. For chains using Substrate, this could cause critical severity issues if an attacker is able to craft a malicious payload in order to trigger the unwrap. 

You can find an image of a malicious payload that will cause a panic below.
image

Below is an example of a fix that could be used : 

```rust
   if decode::is_last(b[i]) {
      match decode::u64(&b[..=i]) {
        Ok(val) => return Ok(val.0),
        Err(_) => return Err(Error::VarIntDecodeError),
      }
    }
```

### PR DESCRIPTION
**Pull request by vmx**
If a varint it non-minimally encoded in a no_std environment, don't panic, but return an error.

Fixes #282.

### CODE REVIEW

File: src/multihash.rs [hunk 1]
```diff
@@ -307,7 +307,10 @@ pub(crate) fn read_u64<R: io::Read>(mut r: R) -> Result<u64, Error> {
         if n == 0 {
             return Err(Error::insufficient_varint_bytes());
         } else if decode::is_last(b[i]) {
-            return Ok(decode::u64(&b[..=i]).unwrap().0);
+            match decode::u64(&b[..=i]) {
+                Ok(decoded) => return Ok(decoded.0),
+                Err(_) => return Err(Error::varint_not_minimal()),
+            }
```
[the remark this answers is not in the document]
Comment (vmx) [reply src/multihash.rs]: Thanks, that's even better!

File: src/error.rs [hunk 2]
```diff
@@ -60,6 +60,15 @@ pub(crate) fn unsigned_variant_to_multihash_error(err: unsigned_varint::io::Read
     }
 }
 
+#[cfg(not(feature = "std"))]
+impl From<unsigned_varint::decode::Error> for Error {
```
Comment (vmx) [inline src/error.rs:64]: @thomaseizinger I've implemented this with the `From` trait. Are there any reasons doing it with a function like the other conversions?

I'm even thinking about doing a PR switching the other ones to from traits as well, which seems more idiomatic to me.

Comment (thomaseizinger) [reply src/error.rs:64]: The `From` trait implementation makes this part of the public API. Given that `unsigned_varint` is not yet `1.0`, I'd advise against it because it would mean that we have to also issue a new minor version if we update `unsigned_varint` to a new minor version.

Comment (thomaseizinger) [reply src/error.rs:64]: It is more idiomatic but unfortunately a semver hazard because trait implementations don't stop at the crate boundary.

Comment (thomaseizinger) [reply src/error.rs]: > Though I don't really like it.

I can relate. I also don't like the verbosity. Although I think the trade-off for being able update dependencies without cascading breaking changes up is definitely worth it.

File: src/multihash.rs [hunk 3]
```diff
@@ -307,7 +307,9 @@ pub(crate) fn read_u64<R: io::Read>(mut r: R) -> Result<u64, Error> {
         if n == 0 {
             return Err(Error::insufficient_varint_bytes());
         } else if decode::is_last(b[i]) {
-            return Ok(decode::u64(&b[..=i]).unwrap().0);
+            return decode::u64(&b[..=i])
+                .map(|decoded| decoded.0)
+                .map_err(crate::error::unsigned_varint_decode_to_multihash_error);
```
Comment (thomaseizinger) [inline src/multihash.rs:312]: A suggestion: https://github.com/multiformats/rust-multihash/pull/296

**Review by mxinden — APPROVED** [review]
Looks good to me. Thanks @vmx!
