### PR TITLE
fix: don't panic on non minimal varints

### LINKED ISSUE #282: Unsafe unwrap could cause an application to panic
https://github.com/multiformats/rust-multihash/blob/8e14b1919bb0f60daa63f0b070278a2963603790/src/multihash.rs#L368

The `unwrap()` here might cause some crash using the library if an error occurred. For chains using Substrate, this could cause critical severity issues if an attacker is able to craft a malicious payload in order to trigger the unwrap. 

You can find an image of a malicious payload that will cause a panic below.
image

Below is an example of a fix that could be used : 

```rust
   if decode::is_last(b[i]) {
      match decode::u64(&b[..=i]) {
        Ok(val) => return Ok(val.0),
        Err(_) => return Err(Error::VarIntDecodeError),
      }
    }
```

### PR DESCRIPTION
**Pull request by vmx**
If a varint it non-minimally encoded in a no_std environment, don't panic, but return an error.

Also some minor Clippy warnings were fixed.

Fixes #282.

### CODE REVIEW

File: src/multihash.rs [hunk 1]
```diff
@@ -362,7 +363,9 @@ pub(crate) fn read_u64<R: io::Read>(mut r: R) -> Result<u64, Error> {
         if n == 0 {
             return Err(Error::Varint(decode::Error::Insufficient));
         } else if decode::is_last(b[i]) {
-            return Ok(decode::u64(&b[..=i]).unwrap().0);
+            return decode::u64(&b[..=i])
+                .map(|decoded| decoded.0)
+                .map_err(Error::Varint);
```
Comment (mattheworris) [inline src/multihash.rs:368]: I tested this change with our project and it fixes the panic, Thanks!

**Review by mattheworris — APPROVED** [review]
Thanks for the quick response.

**Review by mxinden — APPROVED** [review]
With my limited knowledge of `rust-multihash`, this looks good to me.
